# Generated by Django 3.2.15 on 2023-08-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
